import { useEffect, useState } from "react"
import { useOutletContext } from "react-router-dom"

function ResidentDashboardPage() {
    const {developmentBackendLink, productionBackendLink, setSuccessAlert, setErrorAlert, navigate} = useOutletContext();

    const user = JSON.parse(sessionStorage.getItem("resident"))

    const [wasteData, setWasteData] = useState([]);

    var currentDate = new Date();
    var currentMonthName = currentDate.toLocaleString('default', {month: 'long' });

    const logWasteSubmit = (event) => {
        event.preventDefault()

        var waste_amount_entered = Number(event.target.waste_amount_entered.value)
        var month_entered = event.target.month_entered.value

        console.log(waste_amount_entered)

        const requestBody = {
            waste_amount_entered: waste_amount_entered,
            month_entered: month_entered,
            resident_id: Number(user.id),
            apartment_id: Number(user.apartment_id),
        }

        const requestOptions = {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify(requestBody),
        }

        fetch(`${developmentBackendLink}/resident-log-waste`, requestOptions)
            .then((response) => response.json())
            .then((data) => {
                if (data.error) {
                    console.log(data.error)
                    setErrorAlert(data.error)
                    return
                }
                if (data.success_message) {
                    setSuccessAlert(data.success_message)
                    window.location.reload()
                }
            })
    }

    useEffect(() => {
        if (!user) {
            navigate("/")
            return
        }
        const requestOptions = {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({id: user.id}),
        }

        fetch(`${developmentBackendLink}/resident-dashboard`, requestOptions)
            .then((response) => response.json())
            .then((data) => {
                console.log(data)
                setWasteData(data.waste_per_month)
            })
    }, [])

    return (
        <div>
            <h1>Resident Dashboard</h1>
            <hr />

            <div className="row">
                <div className="col-lg-7 col-md-7 col-sm-12-col xs-12" style={{"borderRight": "1px solid #fff"}}>
                    <h3>Waste Generated by Month</h3>
                    <table className="table table-dark table-hover table-striped">
                        <thead>
                            <tr>
                                <td>Month</td>
                                <td>Total Waste Generated (kg)</td>
                            </tr>
                        </thead>
                        <tbody>
                            {wasteData.map((w, index) => (
                                <tr key={index}>
                                    <td>{w.month}</td>
                                    <td>{w.waste_amount} kg</td>  
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>

                <div className="col-lg-5 col-md-5 col-sm-12- col-xs-12">
                    <h3>Log Waste Generated</h3>

                    <form onSubmit={logWasteSubmit} method="post">
                        <input type="number" name="waste_amount_entered" id="waste_amount_entered" placeholder="Amount of Waste(kg)" className="form-control" />
                        <select name="month_entered" class="form-select" aria-label="Default select example" style={{"marginTop": "1%"}}>
                            <option selected value={currentMonthName}>{currentMonthName}</option>
                            <option value="January">January</option>
                            <option value="February">February</option>
                            <option value="March">March</option>
                            <option value="April">April</option>
                            <option value="May">May</option>
                            <option value="June">June</option>
                            <option value="July">July</option>
                            <option value="August">August</option>
                            <option value="September">September</option>
                            <option value="October">October</option>
                            <option value="November">November</option>
                            <option value="December">December</option>
                        </select>

                        <button type="submit" className="btn btn-primary" style={{"marginTop": "1%"}}>Log Waste</button>
                    </form>
                </div>
            </div>
        </div>
    )
}

export default ResidentDashboardPage